# Generated by Django 4.1.7 on 2023-03-17 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_author_imag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='imag',
        ),
        migrations.AlterField(
            model_name='entry',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relateds', to='app1.blog'),
        ),
    ]
