# Generated by Django 4.1.7 on 2023-04-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mob', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
