# Generated by Django 4.1.7 on 2023-04-25 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_order_quantityb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='productid',
        ),
    ]
