# Generated by Django 4.1.7 on 2023-04-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_remove_order_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cartid',
        ),
    ]
